# Generated by Django 4.2.3 on 2023-07-28 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rendapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='newplace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name1', models.CharField(max_length=150)),
                ('img1', models.ImageField(upload_to='photos')),
                ('desc1', models.TextField()),
            ],
        ),
    ]
