# Generated by Django 4.2.3 on 2023-07-28 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rendapp', '0002_newplace'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newplace',
            name='img1',
            field=models.ImageField(upload_to='pics'),
        ),
    ]
